version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: tienpm24/react-core
      DOCKER_TAG: latest
    executor: docker/docker

    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  deploy:
    executor: docker/docker
    steps: 
      - add_ssh_keys: 
          fingerprints:
            - "af:dc:ba:f7:2c:f0:4b:ec:a5:8b:f1:75:0a:bf:ee:4c"
      - run: ssh -oStrictHostKeyChecking=no ubuntu@18.159.109.0 "~/./deploy.sh"

workflows:
  pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push