version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.0.1

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: tienpm24/react-core
      DOCKER_TAG: latest
    executor: docker/docker

    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

  deploy:
    executor: docker/docker
    steps: 
      - add_ssh_keys: 
          fingerprints:
            - "7b:fe:b9:2e:de:8c:5e:7b:49:16:a1:01:09:1f:19:e2"
      - run: 
          name: AWS EC2 Deploy
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws
      
            PUBLIC_IP=$(curl ipinfo.io/ip)
       
            AWS_REGION=us-east-2
   
            SG_ID=sg-01f904deea54d9e89
          
            ~/bin/aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id $SG_ID \
              --protocol tcp --port 22 --cidr $PUBLIC_IP/24
          
            sleep 5
          
             ssh -o StrictHostKeyChecking=no ubuntu@18.223.238.36 "./deploy.sh"
      
            ~/bin/aws ec2 revoke-security-group-ingress --region $AWS_REGION --group-id $SG_ID \
              --protocol tcp --port 22 --cidr $PUBLIC_IP/24
           

workflows:
  pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push